addEventListener('storage', event => { if (!matchRoomKey || event.key !== matchRoomKey || !event.newValue) return; const room = JSON.parse(event.newValue); if (room.started && room.players.length === 2 && !running) { joined = true; mode = 'player'; ui.join.textContent = 'PRZECIWNIK ZNALEZIONY // START'; startGame('player'); } });
addEventListener('click', event => { if (event.target.closest('#playerButton')) startCodeMatch(); });
const canvas = document.getElementById('gameCanvas');
const ctx = canvas.getContext('2d');
const auth = { screen: document.getElementById('authScreen'), registerTab: document.getElementById('registerTab'), loginTab: document.getElementById('loginTab'), registerForm: document.getElementById('registerForm'), loginForm: document.getElementById('loginForm'), registerNick: document.getElementById('registerNick'), registerPassword: document.getElementById('registerPassword'), registerNickError: document.getElementById('registerNickError'), loginNick: document.getElementById('loginNick'), loginPassword: document.getElementById('loginPassword'), loginError: document.getElementById('loginError') };
const ownerUi = { panel: document.getElementById('ownerPanel'), target: document.getElementById('ownerTarget'), coins: document.getElementById('ownerCoins'), wizard: document.getElementById('ownerWizard'), message: document.getElementById('ownerMessage'), addAdmin: document.getElementById('addAdminButton'), ban: document.getElementById('banButton'), unban: document.getElementById('unbanButton'), giveCoins: document.getElementById('giveCoinsButton'), giveWizard: document.getElementById('giveWizardButton') };
const OWNER_NICK = 'adam1właściciel';
const OWNER_NICKS = [OWNER_NICK];
let currentUser = '';
function getAccounts() { return JSON.parse(localStorage.getItem('arcanaAccounts') || '{}'); }
function getMap(name) { return JSON.parse(localStorage.getItem(name) || '{}'); }
function saveMap(name, value) { localStorage.setItem(name, JSON.stringify(value)); }
function ensureOwnerAccount() { const accounts = getAccounts(); if (accounts.test123) accounts.test123.role = 'user'; OWNER_NICKS.forEach(nick => { const key = nick.toLowerCase(); if (!accounts[key]) accounts[key] = { nick, password: nick, role: 'owner' }; else accounts[key].role = 'owner'; }); localStorage.setItem('arcanaAccounts', JSON.stringify(accounts)); }
function persistCoins() { const balances = getMap('arcanaBalances'); const accounts = getAccounts(); balances[currentUser.toLowerCase()] = coins; if (accounts[currentUser.toLowerCase()]) accounts[currentUser.toLowerCase()].coins = coins; saveMap('arcanaBalances', balances); localStorage.setItem('arcanaAccounts', JSON.stringify(accounts)); localStorage.setItem('arcanaCoins', coins); }
function finishAuth(nick) { currentUser = nick; const accounts = getAccounts(); const account = accounts[nick.toLowerCase()]; const balances = getMap('arcanaBalances'); coins = Number(balances[nick.toLowerCase()] ?? account?.coins ?? localStorage.getItem('arcanaCoins') ?? 0); ui.playerName.textContent = `GRACZ: ${nick}`; localStorage.setItem('arcanaCurrentUser', nick); ownerUi.panel.classList.toggle('hidden', !['owner', 'admin'].includes(account?.role)); ownerUi.addAdmin.classList.toggle('hidden', !isOwner()); auth.screen.classList.add('hidden'); updateShop(); updateFriends(); }
function showAuthForm(form) { const register = form === 'register'; auth.registerForm.classList.toggle('hidden', !register); auth.loginForm.classList.toggle('hidden', register); auth.registerTab.classList.toggle('active', register); auth.loginTab.classList.toggle('active', !register); }
function registerAccount(event) { event.preventDefault(); const nick = auth.registerNick.value.trim(); const key = nick.toLowerCase(); const accounts = getAccounts(); auth.registerNickError.textContent = ''; if (accounts[key]) { auth.registerNickError.textContent = 'JUŻ KTOŚ MA TAKĄ NAZWĘ'; return; } accounts[key] = { nick, password: auth.registerPassword.value }; localStorage.setItem('arcanaAccounts', JSON.stringify(accounts)); finishAuth(nick); }
function loginAccount(event) { event.preventDefault(); const nick = auth.loginNick.value.trim(); const key = nick.toLowerCase(); const accounts = getAccounts(); const account = accounts[key]; auth.loginError.textContent = ''; if (getMap('arcanaBans')[key]) { auth.loginError.textContent = 'TO KONTO ZOSTAŁO ZBANOWANE'; return; } if (!account || account.password !== auth.loginPassword.value) { auth.loginError.textContent = 'NIEPRAWIDŁOWY NICK LUB HASŁO'; return; } finishAuth(account.nick); }
function ownerTarget() { const key = ownerUi.target.value.trim().toLowerCase(); return key; }
function ownerResult(text) { ownerUi.message.textContent = text; }
function isOwner() { return OWNER_NICKS.includes(currentUser.toLowerCase()); }
function isStaff() { const account = getAccounts()[currentUser.toLowerCase()]; return account?.role === 'owner' || account?.role === 'admin'; }
function addAdmin() { if (!isOwner()) return; const key = ownerTarget(); const accounts = getAccounts(); if (!accounts[key] || key === OWNER_NICK) { ownerResult('NIEPRAWIDŁOWY CEL'); return; } accounts[key].role = 'admin'; localStorage.setItem('arcanaAccounts', JSON.stringify(accounts)); ownerResult(`DODANO ADMINA: ${accounts[key].nick}`); }
function changeBan(banned) { if (!isStaff()) return; const key = ownerTarget(); const accounts = getAccounts(); if (!accounts[key] || (banned && OWNER_NICKS.includes(key))) { ownerResult('NIEPRAWIDŁOWY CEL'); return; } const bans = getMap('arcanaBans'); if (banned) bans[key] = true; else delete bans[key]; saveMap('arcanaBans', bans); ownerResult(banned ? 'GRACZ ZBANOWANY' : `GRACZ ODBANOWANY: ${accounts[key].nick}`); }
function giveCoins() { if (!isStaff()) return; const key = ownerTarget(); const accounts = getAccounts(); const amount = Number(ownerUi.coins.value); if (!accounts[key] || !Number.isFinite(amount) || amount < 1) { ownerResult('NIEPRAWIDŁOWY CEL LUB LICZBA'); return; } const added = Math.floor(amount); const balances = getMap('arcanaBalances'); balances[key] = Number(balances[key] || accounts[key].coins || 0) + added; accounts[key].coins = balances[key]; saveMap('arcanaBalances', balances); localStorage.setItem('arcanaAccounts', JSON.stringify(accounts)); ownerResult(`DODANO ${added} MONET GRACZOWI ${accounts[key].nick}`); }
function giveWizard() { if (!isStaff()) return; const key = ownerTarget(); const accounts = getAccounts(); const id = ownerUi.wizard.value; if (!accounts[key] || (id === 'overlord' && !isOwner())) { ownerResult('TYLKO WŁAŚCICIEL MOŻE NADAĆ WŁADCĘ'); return; } const owned = getMap('arcanaOwned'); owned[key] = Array.from(new Set([...(owned[key] || accounts[key].wizards || []), id])); accounts[key].wizards = owned[key]; saveMap('arcanaOwned', owned); localStorage.setItem('arcanaAccounts', JSON.stringify(accounts)); ownerResult(`${wizards[id].name} DANY GRACZOWI ${accounts[key].nick}`); }
const ui = { start: document.getElementById('startScreen'), reveal: document.getElementById('revealScreen'), revealName: document.getElementById('revealName'), revealPower: document.getElementById('revealPower'), revealMage: document.getElementById('revealMage'), playerName: document.getElementById('playerName'), friendsButton: document.getElementById('friendsButton'), friendsModal: document.getElementById('friendsModal'), friendsClose: document.getElementById('friendsClose'), friendsTab: document.getElementById('friendsTab'), suggestionsTab: document.getElementById('suggestionsTab'), requestsTab: document.getElementById('requestsTab'), friendsView: document.getElementById('friendsView'), suggestionsView: document.getElementById('suggestionsView'), requestsView: document.getElementById('requestsView'), suggestionsList: document.getElementById('suggestionsList'), inviteNick: document.getElementById('inviteNick'), sendInvite: document.getElementById('sendInviteButton'), inviteMessage: document.getElementById('inviteMessage'), friendNick: document.getElementById('friendNick'), addFriend: document.getElementById('addFriendButton'), friendMessage: document.getElementById('friendMessage'), friendsList: document.getElementById('friendsList'), bot: document.getElementById('botButton'), player: document.getElementById('playerButton'), shopButton: document.getElementById('shopButton'), ownedButton: document.getElementById('ownedButton'), shopClose: document.getElementById('shopClose'), detail: document.getElementById('wizardDetail'), wizardName: document.getElementById('wizardName'), wizardPower: document.getElementById('wizardPower'), buy: document.getElementById('buyButton'), use: document.getElementById('useButton'), join: document.getElementById('joinNote'), result: document.getElementById('resultMessage'), coins: document.getElementById('coinsText'), shop: document.getElementById('shop'), score: document.getElementById('scoreText'), mana: document.getElementById('speedText'), manaMeter: document.getElementById('speedMeter'), ward: document.getElementById('altitudeText'), wardMeter: document.getElementById('altitudeMeter'), ammo: document.getElementById('ammoRow'), event: document.getElementById('eventText'), enemies: document.getElementById('enemiesText'), status: document.getElementById('statusText'), radar: document.getElementById('radarContacts'), toast: document.getElementById('toast'), rival: document.getElementById('rivalName') };
const wizards = { apprentice: { name: 'ISKRA', cost: 0, hp: 100, damage: 12, cooldown: .3 }, storm: { name: 'BURZOWY', cost: 180, hp: 90, damage: 10, cooldown: .18 }, guardian: { name: 'STRAŻNIK', cost: 260, hp: 140, damage: 16, cooldown: .38 }, healer: { name: 'UZDROWICIEL', cost: 3000, hp: 110, damage: 11, cooldown: .3, heal: 10, abilityCooldown: 15 }, cloner: { name: 'KLONER', cost: 4000, hp: 100, damage: 12, cooldown: .3, maxClones: 3 }, aegis: { name: 'AEGIS', cost: 3000, hp: 120, damage: 15, cooldown: .3, shield: true }, overlord: { name: 'WŁADCA', cost: 999999999, hp: 1000, damage: 1000, cooldown: .3, shield: true, fullShield: true, invisibility: true, ownerOnly: true } };
const matchCodeInput = document.getElementById('matchCode');
let matchRoomKey = '';
let matchSocket = null, onlineMatch = false, lastNetworkSync = 0;
let coins = Number(localStorage.getItem('arcanaCoins') || 0), selectedWizard = localStorage.getItem('arcanaWizard') || 'apprentice', viewedWizard = 'apprentice';
let W = 0, H = 0, running = false, last = 0, score = 0, mode = 'bot', joined = false, toastClock = 0, ownedOnly = false;
const keys = {};
const p1 = { x: 0, y: 0, hp: 100, maxHp: 100, mana: 100, damage: 12, spellCooldown: .3, abilityCooldown: 0, clones: 0, shield: 0, shieldUsed: false, invisible: false, color: '#72e4d0', accent: '#d8fff2', face: 1, cooldown: 0 };
const p2 = { x: 0, y: 0, hp: 100, mana: 100, color: '#ef7693', accent: '#ffe0e9', face: -1, cooldown: 0 };
let spells = [], particles = [], stars = [], cloneBodies = [];
function resize() { W = canvas.width = innerWidth * devicePixelRatio; H = canvas.height = innerHeight * devicePixelRatio; canvas.style.width = innerWidth + 'px'; canvas.style.height = innerHeight + 'px'; ctx.setTransform(devicePixelRatio, 0, 0, devicePixelRatio, 0, 0); W = innerWidth; H = innerHeight; stars = Array.from({ length: 90 }, () => ({ x: Math.random() * W, y: Math.random() * H, r: Math.random() * 2, a: .25 + Math.random() * .65 })); }
function reset() { const wizard = wizards[selectedWizard]; score = 0; spells = []; particles = []; cloneBodies = []; p1.x = W * .27; p1.y = H * .59; p1.maxHp = wizard.hp; p1.hp = wizard.hp; p1.mana = 100; p1.damage = wizard.damage; p1.spellCooldown = wizard.cooldown; p1.abilityCooldown = 0; p1.clones = 0; p1.cooldown = 0; p1.shield = 0; p1.shieldUsed = false; p1.invisible = false; p2.x = W * .73; p2.y = H * .59; p2.hp = p2.mana = 100; p2.cooldown = 0; updateUI(); }
function getMatchCode() { return matchCodeInput.value.trim().toUpperCase().replace(/[^A-Z0-9]/g, ''); }
function sendNetwork(message) { if (matchSocket?.readyState === WebSocket.OPEN) matchSocket.send(JSON.stringify(message)); }
function handleNetworkMessage(message) { if (message.type === 'waiting') { ui.join.textContent = `CZEKANIE NA GRACZA // KOD ${message.code}`; return; } if (message.type === 'matched') { onlineMatch = true; joined = true; mode = 'player'; ui.join.textContent = 'PRZECIWNIK ZNALEZIONY // START'; if (!running) startGame('player'); return; } if (message.type === 'state') { p2.x = message.x; p2.y = message.y; p2.hp = message.hp; p2.mana = message.mana; p2.invisible = message.invisible; return; } if (message.type === 'spell') { spells.push({ ...message.spell, owner: p2 }); return; } if (message.type === 'damage') { p1.hp -= message.amount; if (p1.hp <= 0) endGame('GRACZ 2'); return; } if (message.type === 'opponent-left') { onlineMatch = false; running = false; ui.start.classList.remove('hidden'); ui.join.textContent = 'PRZECIWNIK OPUŚCIŁ GRĘ'; setToast('PRZECIWNIK OPUŚCIŁ GRĘ'); } }
function startCodeMatch() { const code = getMatchCode(); if (!code || !currentUser) return; if (matchSocket && matchSocket.readyState === WebSocket.OPEN) { setToast('JUŻ SZUKASZ PRZECIWNIKA'); return; } const protocol = location.protocol === 'https:' ? 'wss' : 'ws'; matchSocket = new WebSocket(`${protocol}://${location.host}`); matchSocket.addEventListener('open', () => sendNetwork({ type: 'join', code, nick: currentUser })); matchSocket.addEventListener('message', event => { try { handleNetworkMessage(JSON.parse(event.data)); } catch { setToast('BŁĄD DANYCH POŁĄCZENIA'); } }); matchSocket.addEventListener('close', () => { matchSocket = null; if (onlineMatch) { onlineMatch = false; running = false; ui.start.classList.remove('hidden'); ui.join.textContent = 'POŁĄCZENIE ZERWANE'; } }); mode = 'player'; joined = false; ui.join.textContent = 'ŁĄCZENIE Z SERWEREM...'; }
function syncNetworkState() { const now = performance.now(); if (!onlineMatch || now - lastNetworkSync < 50) return; lastNetworkSync = now; sendNetwork({ type: 'state', x: p1.x, y: p1.y, hp: p1.hp, mana: p1.mana, invisible: p1.invisible }); }
function startGame(selectedMode) { mode = selectedMode; if (mode === 'player' && !joined) { ui.join.textContent = 'NACISNIJ ENTER, ABY DOLACZYC GRACZEM 2'; return; } reset(); running = false; ui.result.classList.add('hidden'); ui.start.classList.add('hidden'); const wizard = wizards[selectedWizard]; ui.revealName.textContent = wizard.name; ui.revealMage.textContent = wizard.name.slice(0, 1); ui.revealPower.textContent = wizard.heal ? `SUPER MOC // LECZENIE ${wizard.heal} HP // ODNOWIENIE ${wizard.abilityCooldown} SEKUND` : wizard.maxClones ? `SUPER MOC // MAKSYMALNIE ${wizard.maxClones} KLONÓW` : wizard.shield ? 'AEGIS SHIELD // -80% OBRAŻEŃ // 10 SEKUND' : `MOC ZAKLĘCIA // ${wizard.damage} OBRAŻEŃ`; ui.reveal.classList.remove('hidden'); ui.status.textContent = 'PREPARING DUEL'; ui.event.textContent = 'CHOOSE YOUR SPELL'; ui.rival.textContent = mode === 'bot' ? 'THE BOT' : 'PLAYER 2'; setTimeout(() => { ui.reveal.classList.add('hidden'); running = true; ui.status.textContent = 'DUEL SYSTEMS ACTIVE'; ui.event.textContent = mode === 'bot' ? 'THE BOT HAS ENTERED THE CIRCLE' : 'TWO MAGES // ONE DESTINY'; }, 1800); }
function joinPlayer() { if (mode === 'player' && !joined) { joined = true; ui.join.textContent = 'GRACZ 2 DOLACZYL // NACISNIJ ENTER'; setToast('GRACZ 2 DOLACZYL'); } }
function endGame(winner) { running = false; const playerWon = winner === 'GRACZ 1'; if (playerWon) { coins += 100; persistCoins(); setToast('+100 MONET ZA ZWYCIĘSTWO'); } ui.result.textContent = playerWon ? 'WYGRAŁEŚ!' : 'PRZEGRAŁEŚ!'; ui.result.classList.remove('hidden'); ui.result.classList.toggle('win', playerWon); ui.result.classList.toggle('loss', !playerWon); ui.start.classList.remove('hidden'); ui.join.textContent = `${winner} WYGRYWA // WYBIERZ TRYB`; ui.status.textContent = 'DUEL COMPLETE'; updateShop(); }
function move(m, dx, dy, dt) { m.x = Math.max(80, Math.min(W - 80, m.x + dx * 230 * dt)); m.y = Math.max(H * .3, Math.min(H * .78, m.y + dy * 180 * dt)); }
function keepApart() { const minimum = 110, dx = p1.x - p2.x, dy = p1.y - p2.y, distance = Math.hypot(dx, dy); if (distance >= minimum) return; const center = Math.max(80 + minimum / 2, Math.min(W - 80 - minimum / 2, (p1.x + p2.x) / 2)); p1.x = center - minimum / 2; p2.x = center + minimum / 2; }
function cast(owner, target, color) { if (!running || owner === target || owner.cooldown > 0 || owner.mana < 16) return; owner.cooldown = owner === p1 ? p1.spellCooldown : .3; owner.mana -= 16; const a = Math.atan2(target.y - owner.y, target.x - owner.x); const spell = { x: owner.x + Math.cos(a) * 28, y: owner.y + Math.sin(a) * 28, vx: Math.cos(a) * 520, vy: Math.sin(a) * 520, life: 1.5, damage: owner === p1 ? p1.damage : 12, color }; spells.push({ ...spell, owner }); if (onlineMatch && owner === p1) sendNetwork({ type: 'spell', spell }); burst(owner.x, owner.y, color, 5); }
function useAbility() { if (!running) return; const wizard = wizards[selectedWizard]; if (wizard.maxClones) { if (p1.clones >= wizard.maxClones) { setToast(`KLONER // LIMIT ${wizard.maxClones} KLONÓW`); return; } p1.clones += 1; cloneBodies.push({ x: p1.x, y: p1.y, slot: p1.clones - 1 }); burst(p1.x, p1.y, '#d89cff', 14); setToast(`KLONER // KLON ${p1.clones}/${wizard.maxClones}`); return; } if (wizard.heal) { if (p1.abilityCooldown > 0) { setToast(`UZDROWICIEL // ODNOWIENIE ${Math.ceil(p1.abilityCooldown)} SEK`); return; } if (p1.hp >= p1.maxHp) { setToast('UZDROWICIEL // HP JEST PEŁNE'); return; } p1.hp = Math.min(p1.maxHp, p1.hp + wizard.heal); p1.abilityCooldown = wizard.abilityCooldown; burst(p1.x, p1.y, '#8dff9a', 14); setToast(`UZDROWICIEL // +${wizard.heal} HP`); return; } if (wizard.invisibility) { p1.invisible = !p1.invisible; setToast(p1.invisible ? 'WŁADCA // NIEWIDZIALNOŚĆ' : 'WŁADCA // WIDOCZNOŚĆ'); return; } if (wizard.shield && !p1.shieldUsed) { p1.shield = 10; p1.shieldUsed = true; setToast('TARCZA // 80% REDUKCJI // 10 SEKUND'); } }
function useShield() { if (!running || !wizards[selectedWizard].fullShield || p1.shieldUsed) return; p1.shield = 10; p1.shieldUsed = true; setToast('WŁADCA // TARCZA 100% // 10 SEKUND'); }
function update(dt) { if (!running) return; move(p1, (keys.KeyD ? 1 : 0) - (keys.KeyA ? 1 : 0), (keys.KeyS ? 1 : 0) - (keys.KeyW ? 1 : 0), dt); const time = performance.now() / 1000; cloneBodies.forEach(clone => { const angle = clone.slot * Math.PI * 2 / 3 + time * .7; const targetX = p1.x + Math.cos(angle) * 62; const targetY = p1.y + Math.sin(angle) * 38; clone.x += (targetX - clone.x) * Math.min(1, dt * 5); clone.y += (targetY - clone.y) * Math.min(1, dt * 5); }); if (mode === 'player' && !onlineMatch) move(p2, (keys.ArrowRight ? 1 : 0) - (keys.ArrowLeft ? 1 : 0), (keys.ArrowDown ? 1 : 0) - (keys.ArrowUp ? 1 : 0), dt); else if (!onlineMatch) { move(p2, p1.x > p2.x + 30 ? 1 : p1.x < p2.x - 30 ? -1 : 0, p1.y > p2.y + 25 ? 1 : p1.y < p2.y - 25 ? -1 : 0, dt); if (!p1.invisible && Math.random() < dt * .8) cast(p2, p1, p2.color); } keepApart(); p1.cooldown = Math.max(0, p1.cooldown - dt); p1.abilityCooldown = Math.max(0, p1.abilityCooldown - dt); p2.cooldown = Math.max(0, p2.cooldown - dt); p1.shield = Math.max(0, p1.shield - dt); p1.mana = Math.min(100, p1.mana + dt * 8); p2.mana = Math.min(100, p2.mana + dt * 8); if (keys.Space) cast(p1, p2, p1.color); if (mode === 'player' && !onlineMatch && (keys.Numpad0 || keys.Digit0)) cast(p2, p1, p2.color); spells.forEach(s => { s.x += s.vx * dt; s.y += s.vy * dt; s.life -= dt; const target = s.owner === p1 ? p2 : p1; if (s.life > 0 && Math.hypot(s.x - target.x, s.y - target.y) < 36) { const damage = target === p1 && p1.shield > 0 ? (wizards[selectedWizard].fullShield ? 0 : s.damage * .2) : s.damage; target.hp -= damage; if (onlineMatch && target === p1) sendNetwork({ type: 'damage', amount: damage }); burst(target.x, target.y, s.color, 12); s.life = 0; if (target.hp <= 0) endGame(s.owner === p1 ? 'GRACZ 1' : mode === 'bot' ? 'BOT' : 'GRACZ 2'); } }); spells = spells.filter(s => s.life > 0 && s.x > -40 && s.x < W + 40 && s.y > -40 && s.y < H + 40); particles.forEach(p => { p.x += p.vx * dt; p.y += p.vy * dt; p.life -= dt; }); particles = particles.filter(p => p.life > 0); toastClock -= dt; syncNetworkState(); updateUI(); }
function burst(x, y, color, n) { for (let i = 0; i < n; i++) { const a = Math.random() * Math.PI * 2, s = 25 + Math.random() * 130; particles.push({ x, y, vx: Math.cos(a) * s, vy: Math.sin(a) * s, life: .3 + Math.random() * .5, color, size: 2 + Math.random() * 3 }); } }
function setToast(text) { ui.toast.textContent = text; ui.toast.classList.add('show'); toastClock = 1.2; }
function updateShop() { const accounts = getAccounts(); const accountOwned = accounts[currentUser.toLowerCase()]?.wizards || []; const owned = Array.from(new Set([...(getMap('arcanaOwned')[currentUser.toLowerCase()] || []), ...accountOwned])); ui.coins.textContent = coins; ui.shop.querySelectorAll('.wizard-card[data-wizard]').forEach(card => { const wizard = wizards[card.dataset.wizard]; if (!wizard) return; const selected = card.dataset.wizard === selectedWizard; const hasWizard = wizard.cost === 0 || owned.includes(card.dataset.wizard); const available = hasWizard || (!wizard.ownerOnly && wizard.cost <= coins) || selected; card.classList.toggle('hidden', ownedOnly && !hasWizard); card.classList.toggle('locked', !available); card.classList.toggle('selected', selected); card.querySelector('span').textContent = selected ? 'WYBRANY' : wizard.ownerOnly && !hasWizard ? 'TYLKO WŁAŚCICIEL' : hasWizard ? 'POSIADANY' : wizard.cost === 0 ? 'DARMOWY' : `${wizard.cost} MONET // KUP`; }); }
function escapeHtml(value) { return value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character])); }
function updateFriends() { const key = currentUser.toLowerCase(); const friends = getMap('arcanaFriends')[key] || []; const requests = getMap('arcanaFriendRequests')[key] || []; ui.friendsList.innerHTML = friends.length ? friends.map(nick => `<div class="friend-item">${escapeHtml(nick)}</div>`).join('') : '<div class="friends-empty">BRAK ZNAJOMYCH</div>'; ui.suggestionsList.innerHTML = requests.length ? requests.map(nick => `<div class="friend-item friend-request"><span>${escapeHtml(nick)}</span><span class="friend-request-actions"><button type="button" data-accept="${encodeURIComponent(nick)}">✓</button><button type="button" data-reject="${encodeURIComponent(nick)}">X</button></span></div>`).join('') : '<div class="friends-empty">BRAK ZAPROSZEŃ</div>'; }
function setFriendsTab(tab) { const tabs = { friends: [ui.friendsTab, ui.friendsView], suggestions: [ui.suggestionsTab, ui.suggestionsView], requests: [ui.requestsTab, ui.requestsView] }; Object.entries(tabs).forEach(([name, [button, view]]) => { button.classList.toggle('active', name === tab); view.classList.toggle('hidden', name !== tab); }); }
function sendFriendInvite() { const nick = ui.inviteNick.value.trim(); const key = nick.toLowerCase(); const accounts = getAccounts(); ui.inviteMessage.textContent = ''; if (!accounts[key]) { ui.inviteMessage.textContent = 'NIE ZNALEZIONO TAKIEGO GRACZA'; return; } if (key === currentUser.toLowerCase()) { ui.inviteMessage.textContent = 'NIE MOŻESZ ZAPROSIĆ SIEBIE'; return; } const friendsMap = getMap('arcanaFriends'); const friends = friendsMap[currentUser.toLowerCase()] || []; if (friends.some(friend => friend.toLowerCase() === key)) { ui.inviteMessage.textContent = 'TEN GRACZ JUŻ JEST ZNAJOMYM'; return; } const requestsMap = getMap('arcanaFriendRequests'); const requests = requestsMap[key] || []; if (requests.some(request => request.toLowerCase() === currentUser.toLowerCase())) { ui.inviteMessage.textContent = 'ZAPROSZENIE JUŻ WYSŁANE'; return; } requests.push(currentUser); requestsMap[key] = requests; saveMap('arcanaFriendRequests', requestsMap); ui.inviteNick.value = ''; ui.inviteMessage.textContent = 'ZAPROSZENIE WYSŁANE'; }
function respondToFriendInvite(nick, accepted) { const key = currentUser.toLowerCase(); const requestsMap = getMap('arcanaFriendRequests'); const requests = requestsMap[key] || []; const index = requests.findIndex(request => request.toLowerCase() === nick.toLowerCase()); if (index < 0) return; const sender = requests[index]; requests.splice(index, 1); requestsMap[key] = requests; saveMap('arcanaFriendRequests', requestsMap); if (accepted) { const friendsMap = getMap('arcanaFriends'); const ownFriends = friendsMap[key] || []; const senderKey = sender.toLowerCase(); const senderFriends = friendsMap[senderKey] || []; if (!ownFriends.some(friend => friend.toLowerCase() === senderKey)) ownFriends.push(sender); if (!senderFriends.some(friend => friend.toLowerCase() === key)) senderFriends.push(currentUser); friendsMap[key] = ownFriends; friendsMap[senderKey] = senderFriends; saveMap('arcanaFriends', friendsMap); } updateFriends(); }
function openWizard(id) { viewedWizard = id; const wizard = wizards[id]; const accounts = getAccounts(); const owned = Array.from(new Set([...(getMap('arcanaOwned')[currentUser.toLowerCase()] || []), ...(accounts[currentUser.toLowerCase()]?.wizards || [])])); const hasWizard = wizard.cost === 0 || owned.includes(id); const power = wizard.maxClones ? `Moc: TWORZENIE KLONÓW, MAKSYMALNIE ${wizard.maxClones}` : wizard.heal ? `Moc: LECZENIE ${wizard.heal} HP, ODNOWIENIE ${wizard.abilityCooldown} SEKUND` : wizard.ownerOnly ? 'Moc: NIEWIDZIALNOŚĆ BEZ LIMITU + TARCZA 100% PRZEZ 10 SEKUND' : wizard.shield ? 'Moc: TARCZA PRZEZ 10 SEKUND, REDUKUJE OBRAŻENIA' : `Moc zaklęcia: ${wizard.damage}`; ui.wizardName.textContent = wizard.name; ui.wizardPower.textContent = `${power} | ${wizard.damage} OBRAŻEŃ | ${wizard.hp} HP | Cena: ${wizard.ownerOnly ? 'TYLKO TEST123' : wizard.cost === 0 ? 'darmowy' : wizard.cost + ' monet'}`; ui.buy.textContent = hasWizard ? 'POSIADANY' : 'KUP'; ui.buy.disabled = hasWizard; ui.use.disabled = !hasWizard || id === selectedWizard; ui.detail.classList.remove('hidden'); }
function closeWizard() { ui.detail.classList.add('hidden'); }
function removeWizard() { selectedWizard = 'apprentice'; localStorage.setItem('arcanaWizard', selectedWizard); updateShop(); setToast('CZARODZIEJ ZDJĘTY'); }
function buyWizard(id) { const wizard = wizards[id]; const owned = getMap('arcanaOwned'); const accounts = getAccounts(); const playerOwned = Array.from(new Set([...(owned[currentUser.toLowerCase()] || []), ...(accounts[currentUser.toLowerCase()]?.wizards || [])])); if (wizard.ownerOnly && !isOwner() && !playerOwned.includes(id)) { setToast('WŁADCĘ MOŻE NADAĆ TYLKO TEST123'); return; } if (playerOwned.includes(id) || wizard.cost === 0) return; if (coins < wizard.cost) { setToast('NIE STAĆ CIĘ'); return; } coins -= wizard.cost; playerOwned.push(id); owned[currentUser.toLowerCase()] = playerOwned; accounts[currentUser.toLowerCase()].wizards = playerOwned; saveMap('arcanaOwned', owned); localStorage.setItem('arcanaAccounts', JSON.stringify(accounts)); persistCoins(); setToast(`${wizard.name} KUPIONY // DODANO DO POSIADANYCH`); updateShop(); openWizard(id); }
function useWizard(id) { const wizard = wizards[id]; const accounts = getAccounts(); const owned = Array.from(new Set([...(getMap('arcanaOwned')[currentUser.toLowerCase()] || []), ...(accounts[currentUser.toLowerCase()]?.wizards || [])])); if (wizard.cost > 0 && !owned.includes(id)) return; selectedWizard = id; localStorage.setItem('arcanaWizard', selectedWizard); updateShop(); openWizard(id); setToast(`${wizard.name} UŻYWANY`); }
function updateUI() { ui.score.textContent = String(score).padStart(6, '0'); ui.mana.textContent = Math.round(p1.mana); ui.manaMeter.style.width = `${p1.mana}%`; ui.ward.textContent = Math.max(0, Math.round(p1.hp)); ui.wardMeter.style.width = `${Math.max(0, p1.hp)}%`; ui.enemies.textContent = `${mode === 'player' ? 'MAGE 2' : 'BOT'} WARD ${Math.max(0, Math.round(p2.hp))}%`; ui.radar.innerHTML = `<i class="radar-contact" style="left:${50 + (p2.x - p1.x) / W * 100}%;top:${50 + (p2.y - p1.y) / H * 100}%"></i>`; ui.ammo.innerHTML = Array.from({ length: 6 }, (_, i) => `<i class="ammo ${i >= Math.floor(p1.mana / 16) ? 'empty' : ''}"></i>`).join(''); if (toastClock <= 0) ui.toast.classList.remove('show'); }
function draw() { const bg = ctx.createRadialGradient(W * .5, H * .45, 20, W * .5, H * .5, Math.max(W, H) * .7); bg.addColorStop(0, '#4a3164'); bg.addColorStop(.5, '#1d294b'); bg.addColorStop(1, '#0a1227'); ctx.fillStyle = bg; ctx.fillRect(0, 0, W, H); stars.forEach(s => { ctx.globalAlpha = s.a; ctx.fillStyle = '#f9ddb0'; ctx.fillRect(s.x, s.y, s.r, s.r); }); ctx.globalAlpha = 1; ctx.save(); ctx.translate(W / 2, H * .62); ctx.strokeStyle = 'rgba(241,195,120,.45)'; ctx.lineWidth = 2; ctx.beginPath(); ctx.ellipse(0, 0, Math.min(W * .37, 450), Math.min(H * .16, 125), 0, 0, Math.PI * 2); ctx.stroke(); ctx.restore(); spells.forEach(s => { ctx.save(); ctx.shadowColor = s.color; ctx.shadowBlur = 18; ctx.fillStyle = s.color; ctx.beginPath(); ctx.arc(s.x, s.y, 8, 0, Math.PI * 2); ctx.fill(); ctx.restore(); }); particles.forEach(p => { ctx.globalAlpha = Math.max(0, p.life * 1.8); ctx.fillStyle = p.color; ctx.fillRect(p.x, p.y, p.size, p.size); }); ctx.globalAlpha = 1; const playerLabel = currentUser || 'GRACZ 1'; const rivalLabel = mode === 'bot' ? 'BOT' : 'GRACZ 2'; drawMage(p1, playerLabel); cloneBodies.forEach(clone => drawMage({ ...p1, x: clone.x, y: clone.y }, playerLabel)); drawMage(p2, rivalLabel); }
function drawMage(m, label) { if (m === p1 && p1.invisible) return; ctx.save(); ctx.translate(m.x, m.y); if (m === p1 && p1.shield > 0) { ctx.strokeStyle = `rgba(114,228,208,${.45 + Math.sin(performance.now() / 120) * .15})`; ctx.lineWidth = 3; ctx.shadowColor = '#72e4d0'; ctx.shadowBlur = 22; ctx.beginPath(); ctx.arc(0, 0, 68, 0, Math.PI * 2); ctx.stroke(); } ctx.shadowColor = m.color; ctx.shadowBlur = 16; ctx.fillStyle = m.color; ctx.beginPath(); ctx.moveTo(0, -52); ctx.lineTo(28, 4); ctx.lineTo(22, 34); ctx.lineTo(0, 48); ctx.lineTo(-22, 34); ctx.lineTo(-28, 4); ctx.closePath(); ctx.fill(); ctx.shadowBlur = 0; ctx.fillStyle = '#211934'; ctx.beginPath(); ctx.arc(0, -23, 15, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = m.accent; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(m.face * 18, 13); ctx.lineTo(m.face * 42, -18); ctx.stroke(); ctx.fillStyle = m.accent; ctx.font = '700 11px Space Grotesk'; ctx.textAlign = 'center'; ctx.fillText(label, 0, 67); ctx.restore(); }
function frame(t) { const dt = Math.min(.035, (t - last) / 1000 || 0); last = t; update(dt); draw(); requestAnimationFrame(frame); }
addEventListener('resize', resize); addEventListener('keydown', e => { keys[e.code] = true; if (e.code === 'Space') e.preventDefault(); if (e.code === 'KeyE') useAbility(); if (e.code === 'KeyQ') useShield(); if (e.code === 'Enter') { joinPlayer(); if (!running && joined && mode === 'player') startGame('player'); } if (e.code === 'KeyR' && running) startGame(mode); }); addEventListener('keyup', e => { keys[e.code] = false; }); ui.bot.addEventListener('click', () => startGame('bot')); ui.player.addEventListener('click', () => startGame('player')); ui.shopButton.addEventListener('click', () => { ownedOnly = false; ui.shop.classList.remove('hidden'); closeWizard(); updateShop(); }); ui.ownedButton.addEventListener('click', () => { ownedOnly = true; ui.shop.classList.remove('hidden'); closeWizard(); updateShop(); }); ui.shopClose.addEventListener('click', () => { ownedOnly = false; ui.shop.classList.add('hidden'); }); ui.shop.querySelectorAll('.wizard-card').forEach(card => card.addEventListener('click', () => openWizard(card.dataset.wizard))); document.getElementById('exitButton').addEventListener('click', closeWizard); ui.buy.addEventListener('click', () => buyWizard(viewedWizard)); ui.use.addEventListener('click', () => useWizard(viewedWizard)); resize(); reset(); updateShop(); requestAnimationFrame(frame);
auth.registerTab.addEventListener('click', () => showAuthForm('register')); auth.loginTab.addEventListener('click', () => showAuthForm('login')); auth.registerForm.addEventListener('submit', registerAccount); auth.loginForm.addEventListener('submit', loginAccount); ownerUi.addAdmin.addEventListener('click', addAdmin); ownerUi.ban.addEventListener('click', () => changeBan(true)); ownerUi.unban.addEventListener('click', () => changeBan(false)); ownerUi.giveCoins.addEventListener('click', giveCoins); ownerUi.giveWizard.addEventListener('click', giveWizard); ui.friendsButton.addEventListener('click', () => { setFriendsTab('friends'); ui.friendsModal.classList.remove('hidden'); ui.inviteMessage.textContent = ''; updateFriends(); }); ui.friendsTab.addEventListener('click', () => setFriendsTab('friends')); ui.requestsTab.addEventListener('click', () => setFriendsTab('requests')); ui.suggestionsTab.addEventListener('click', () => setFriendsTab('suggestions')); ui.friendsClose.addEventListener('click', () => ui.friendsModal.classList.add('hidden')); ui.sendInvite.addEventListener('click', sendFriendInvite); ui.suggestionsList.addEventListener('click', event => { const accept = event.target.closest('[data-accept]'); const reject = event.target.closest('[data-reject]'); if (accept) respondToFriendInvite(decodeURIComponent(accept.dataset.accept), true); if (reject) respondToFriendInvite(decodeURIComponent(reject.dataset.reject), false); }); ensureOwnerAccount(); showAuthForm('register');