services:
  - type: web
    name: walka-czarodziejow
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
